language: python

sudo: false

env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11.*

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

install:
    - pip install -q coveralls mock Django==$DJANGO_VERSION

script:
    coverage run --source=djangocache manage.py test tests

after_success:
    coveralls

branches:
  only:
    - master
